### ISSUE TITLE
Error generated : bme280.load_calibration_params

### ISSUE THREAD

**Issue by quintendewilde** [rm-hull/bme280#4]
Following error generated when testing the example. 

when I message : bme280.load_calibration_params(bus, address)

```
>>> bme280.load_calibration_params(bus, address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'address' is not defined
>>> data = bme280.sample(bus, address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'address' is not defined
>>> print(data.id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
>>> bme280.load_calibration_params(bus, address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'address' is not defined

```

**Comment by rm-hull** [comment]
Sounds like you haven't declared a value for the address. Try:

```python
address = 0x76
```

and try again
